version: '3'
services:
  mongo:
    image: mongo:3.6.17-xenial
    restart: always
    ports: 
      - "8000:27017"
    volumes: 
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root