version: '3'
services:
  api:
    container_name: avengers-api
    restart: always
    env_file:
      - .env
    build: .
    ports: 
      - "8001:8001"
    networks: 
      - avengers

  mongo:
    image: mongo:3.6.17-xenial
    restart: always
    ports: 
      - "8000:27017"
    volumes: 
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks: 
      - avengers

  nginx:
    build: ./front/
    container_name: avengers-nginx
    restart: always
    env_file: 
      - ./front/.env
    ports:
      - "8002:3000"
    networks: 
      - avengers
networks:
  avengers: